package by.training.finance.controller;

public enum CommandName {

    ADD_EXPENSE, EDIT_EXPENSE, DELETE_EXPENSE,
    ADD_INCOME, EDIT_INCOME, DELETE_INCOME,

    GET_TRANSACTIONS_HISTORY,

    GET_EXPENSES_BY_ID, CLEAR_TRANSACTION_HISTORY
}